"""Shared MPC baseline configuration."""

MPC_DT = 0.1
MPC_WHEELBASE_M = 2.7

MPC_HORIZON = 15

MPC_Q_LATERAL = 10.0
MPC_Q_HEADING = 1.0
MPC_R_STEERING = 1.0

MPC_MAX_STEERING_ANGLE = 0.5
MPC_MAX_STEERING_RATE = 0.5