from dataclasses import dataclass
from enum import Enum

@dataclass
class ReferencePoint:
    """A geometric point on the reference line."""

    x: float
    y: float
    s: float
    yaw: float
    curvature: float

@dataclass
class VehicleState:
    """State of the ego vehicle in the global Cartesian coordinate frame."""

    x: float
    y: float
    yaw: float
    speed: float


@dataclass
class ControlCommand:
    """Control input applied to the vehicle."""

    acceleration: float     # m/s^2, positive for acceleration.
    steering_angle: float   # rad, positive for left steering.


@dataclass
class ScenarioState:
    """Structured information about the driving environment."""

    speed_limit_mps: float

    lead_vehicle_distance_m: float | None = None
    lead_vehicle_speed_mps: float | None = None

    pedestrian_distance_m: float | None = None
    pedestrian_crossing: bool = False


class BehaviorType(Enum):
    """Supported high-level driving behaviors."""

    KEEP_LANE = "KEEP_LANE"
    SLOW_DOWN = "SLOW_DOWN"
    STOP = "STOP"
    YIELD = "YIELD"


@dataclass
class BehaviorCommand:
    """High-level driving command generated by a behavior planner."""

    behavior: BehaviorType
    target_speed_mps: float
    reason: str
    confidence: float | None = None


@dataclass
class TrajectoryPoint:
    """A reference point on a planned trajectory."""

    x: float
    y: float
    yaw: float
    speed: float
    time: float


@dataclass
class FrenetPoint:
    """A point expressed in the Frenet / SL coordinate frame."""

    s: float
    l: float